import {
  BarChart3,
  Users,
  FileText,
  FileCheck,
  FileSignature,
  Calendar,
  UserCheck,
  Briefcase,
  Image,
  MessageSquare,
  DollarSign,
  TrendingUp,
  ClipboardList,
  Heart,
  Layout,
  FileType,
  Mail,
  Globe,
  Settings,
  Home
} from 'lucide-react';

export const menuItems = [
  { id: 'dashboard', label: 'Dashboard', icon: 'BarChart3' },
  { id: 'leads', label: 'Leads', icon: 'Users' },
  { id: 'quotes', label: 'Orçamentos', icon: 'FileText' },
  { id: 'proposals', label: 'Propostas', icon: 'FileCheck' },
  { id: 'contracts', label: 'Contratos', icon: 'FileSignature' },
  { id: 'events', label: 'Eventos', icon: 'Calendar' },
  { id: 'clients', label: 'Clientes', icon: 'UserCheck' },
  { id: 'professionals', label: 'Profissionais', icon: 'Users' },
  { id: 'services', label: 'Serviços', icon: 'Briefcase' },
  { id: 'cms-home', label: 'CMS Home', icon: 'Home' },
  { id: 'gallery', label: 'Galeria', icon: 'Image' },
  { id: 'testimonials', label: 'Depoimentos', icon: 'MessageSquare' },
  { id: 'vendas-financeiro', label: 'Vendas & Financeiro', icon: 'DollarSign' },
  { id: 'gestao-comercial', label: 'Gestão Comercial', icon: 'TrendingUp' },
  { id: 'questionarios', label: 'Questionários', icon: 'ClipboardList' },
  { id: 'historias-casais', label: 'Histórias de Casais', icon: 'Heart' },
  { id: 'proposal-templates', label: 'Templates Propostas', icon: 'Layout' },
  { id: 'contract-templates', label: 'Templates Contratos', icon: 'FileType' },
  { id: 'contract-email-templates', label: 'Templates Email Contratos', icon: 'Mail' },
  { id: 'website', label: 'Website', icon: 'Globe' },
  { id: 'settings', label: 'Configurações', icon: 'Settings' }
];
