// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oampddkpuybkbwqggrty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hbXBkZGtwdXlia2J3cWdncnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2OTMyMzcsImV4cCI6MjA2MzI2OTIzN30.JDLVGgm_lgTDxOWWys2IssWOVqd6tTFpfMhXzhoZv3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);